nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: loose
checksumBehavior: update
yarnPath: .yarn/releases/yarn-3.5.1.cjs

packageExtensions:
  '@coinbase/wallet-sdk@*':
    peerDependencies:
      '@babel/core': '^7.18.2'
  '@nomiclabs/hardhat-waffle@*':
    dependencies:
      chai: '^4.3.6'
  '@openzeppelin/hardhat-upgrades@*':
    peerDependencies:
      ethers: '^5.6.8'
  '@typechain/hardhat@*':
    dependencies:
      '@ethersproject/abi': '^5.6.1'
      '@ethersproject/providers': '^5.6.1'
      typescript: '^4.7.3'
  '@typechain/ethers-v5@*':
    dependencies:
      '@ethersproject/abi': '^5.6.1'
      '@ethersproject/bytes': '^5.6.1'
      '@ethersproject/providers': '^5.6.1'
      typescript: '^4.7.3'
  async@2.6.4:
    dependencies:
      lodash: '^4.17.21'
  debug@*:
    dependencies:
      supports-color: '*'
  # awaiting fix: https://github.com/facebook/create-react-app/issues/11982
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      '@babel/plugin-syntax-flow':
        optional: true
      '@babel/plugin-transform-react-jsx':
        optional: true
  eth-block-tracker@*:
    peerDependencies:
      '@babel/core': '^7.18.2'
  hardhat-deploy@*:
    dependencies:
      '@ethersproject/abi': '^5.6.1'
      '@ethersproject/address': '^5.6.1'
      '@ethersproject/bytes': '^5.6.1'
      '@ethersproject/bignumber': '^5.6.1'
      '@ethersproject/constants': '^5.6.1'
      '@ethersproject/contracts': '^5.6.1'
      '@ethersproject/hash': '^5.6.1'
      '@ethersproject/providers': '^5.6.1'
      '@ethersproject/solidity': '^5.6.1'
      '@ethersproject/transactions': '^5.6.1'
      '@ethersproject/wallet': '^5.6.1'
      '@ethersproject/web': '^5.6.1'
    peerDependencies:
      hardhat: '^2.9.1'
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: '*'
      webpack: '>=5.76.0'
  typechain@*:
    dependencies:
      typescript: '^4.7.3'
  wagmi@*:
    peerDependencies:
      '@babel/core': '^7.18.2'
