nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpMode: loose
checksumBehavior: update
yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
  # awaiting fix: https://github.com/facebook/create-react-app/issues/11982
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      '@babel/plugin-syntax-flow':
        optional: true
      '@babel/plugin-transform-react-jsx':
        optional: true
  # awaiting fix: https://github.com/facebook/create-react-app/pull/11526
  react-dev-utils@*:
    peerDependencies:
      typescript: ">=2.7"
      webpack: ">=4"
  eth-block-tracker@*:
    peerDependencies:
      "@babel/core": "^7.18.2"
  "@coinbase/wallet-sdk@*":
    peerDependencies:
      "@babel/core": "^7.18.2"
  wagmi@*:
    peerDependencies:
      "@babel/core": "^7.18.2"
  "@openzeppelin/hardhat-upgrades@*":
    peerDependencies:
      ethers: "^5.6.8"
      "@ethersproject/abi": "^5.6.3"
  hardhat-deploy@*:
    peerDependencies:
      hardhat: "^2.9.1"
